name: my workflow
on: 
  # run on all branches
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: show message
        run: echo "Running first message"
      - name: code checkout
        uses: actions/checkout@v3
      - name: setip dot net core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name : build the app
        run : dotnet build
    notify:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: send notification
        uses: dineshppatilgmi/ms-teams-notification@v1.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}   
          message: "This is from custom actions created." 
  