name: my workflow
on: 
  # run on all branches
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: show message
        run: echo "Running first message"
      - name: code checkout
        uses: actions/checkout@v3
      - name: setip dot net core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name : build the app
        run : dotnet build
  notify:
    runs-on: ubuntu-latest
    if: always() # This is needed when we are 
    needs:
      - build
    steps:
      - name: send notification
        uses: dineshppatilgmi/ms-teams-notification@v1.3
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}   
          message: "Github Action number ${{ github.run_number }} for ${{ github.repository }} triggered by ${{ github.actor }} is completed with ${{ needs.build.result }} status."
 
  